version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-android:
    executor: android/android

    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - run:
          name: Run Android build
          command: ./gradlew androidApp:assembleDebug

workflows:
  build-all:
    jobs:
      - build-android
